### ISSUE TITLE
2.0.4 require Cloudflare?

### ISSUE THREAD

**Issue by clover1980** [pinokiocomputer/pinokio#183]
Hi,
Can someone explain why new version required "cloudflared" for all installed apps? I wasn't able to find any release notes.
In older version same apps works still great without Cloudflare. Is it Cloudflare cloud services? Cloudflare inc have really bad reputation in many communities by their practice of networks monopolization and geo/racial filtering instruments provided for web administrators by default (which leads to collapse of global network, many examples, the most oldest is block filter by country to Sony firmwares private repository made by japanese owner). It's not comfortable to share our work in apps with such corporation.

**Comment by cocktailpeanut** [comment]
Release notes https://github.com/pinokiocomputer/pinokio/releases/tag/2.0.1

Look under the "public nodes" section.

The `cloudflared` module is simply a module that lets you use cloudflare tunnel ONLY IF you want it. It's off by default. You can turn it on in the share menu if you want. Otherwise you don't have to worry about anything.

Speaking of privacy, Pinokio 2 even turns off local network sharing by default and gives users option to turn it on ONLY if they want.

If you would like to stay updated on all these things, please follow me on X (@cocktailpeanut) or join the discord where I make announcements.
